(********************************************************************
 * COPYRIGHT --  
 ********************************************************************
 * Program: IPConfig
 * File: IPConfigInit.st
 * Author: wallisj
 * Created: July 17, 2008
 ********************************************************************
 * Implementation of program IPConfig
 ********************************************************************)

PROGRAM _INIT

	ReadEthernetSettings := TRUE;


END_PROGRAM

