TYPE
	CONFIG_MA_CYCLIC_POS_typ : STRUCT
		node_number	: UINT ;
		send_parid	: UINT ;
	END_STRUCT;
	BITOFFSET_typ : STRUCT
		node_number	: UINT ;
		offset	: UINT ;
		bits_to_shift	: UINT ;
	END_STRUCT;
	AxisInstrumentation_typ : STRUCT
		StatorCurrent	: REAL ;
		TempModel	: REAL ;
		TempSensor	: REAL ;
		JuctionTemp	: REAL ;
		BleederTemp	: REAL ;
		DCBusVoltage	: REAL ;
		LagError	: REAL ;
		ActPosition	: REAL ;
		ActVelocity	: REAL ;
		ActTorque	: REAL ;
		ActVelocityRPS	: REAL ;
	END_STRUCT;
	AxisControl_typ : STRUCT
		SaveInitPar	: BOOL ;
		Rotary	: BOOL ;
		ControlOn	: BOOL ;
		Reset	: BOOL ;
		HomePermit	: BOOL ;
		Home	: BOOL ;
		MovePermit	: BOOL ;
		StartAbsMove	: ARRAY[0..8] OF BOOL ;
		StartVelMove	: ARRAY[0..1] OF BOOL ;
		StartSyncMove	: BOOL ;
		StopSyncMove	: BOOL ;
		Stop	: BOOL ;
		JogPos	: BOOL ;
		JogNeg	: BOOL ;
		JogStop	: BOOL ;
		SpeedOvR	: REAL ;
		AccDecOvR	: REAL ;
		AckOne	: BOOL ;
		AckAll	: BOOL ;
	END_STRUCT;
	MSG_TEXT_typ : STRUCT
		line1	: STRING[79] ;
		line2	: STRING[79] ;
		line3	: STRING[79] ;
		line4	: STRING[79] ;
	END_STRUCT;
	AxisStatus_typ : STRUCT
		ControllerOn	: BOOL ;
		HomedOK	: BOOL ;
		AbsMoveInPos	: ARRAY[0..8] OF BOOL ;
		VelMoveInVel	: ARRAY[0..1] OF BOOL ;
		Errorstop	: BOOL ;
		Disabled	: BOOL ;
		Stopping	: BOOL ;
		StandStill	: BOOL ;
		DiscreteMotion	: BOOL ;
		ContinuousMotion	: BOOL ;
		SynchronisedMotion	: BOOL ;
		Homing	: BOOL ;
		Moving	: BOOL ;
		JoggingPos	: BOOL ;
		JoggingNeg	: BOOL ;
		FaultAct	: BOOL ;
		NumOfFaults	: UINT ;
		FaultNum	: UINT ;
		FaultTxt	: MSG_TEXT_typ ;
		FaultStatus	: UINT ;
		HomeStatus	: UINT ;
		DriveStatus	: UDINT ;
		BrakeStatus	: UDINT ;
		EnableSw	: BOOL ;
		NegSw	: BOOL ;
		PosSw	: BOOL ;
		RefSw	: BOOL ;
		Trigger1	: BOOL ;
		Trigger2	: BOOL ;
		DriveReady	: BOOL ;
		BrakeRelayOn	: BOOL ;
		BrakeElectricalOn	: BOOL ;
		BrakeMechanicalOpen	: BOOL ;
	END_STRUCT;
	AxisControlAndStatus_typ : STRUCT
		pAxisObject	: UDINT ;
		pAxisCtrl	: UDINT ;
		strAxisInit	: STRING[8] ;
		Node	: USINT ;
		Control	: AxisControl_typ ;
		Status	: AxisStatus_typ ;
		Instrumentation	: AxisInstrumentation_typ ;
	END_STRUCT;
	AxisMoveSync_typ : STRUCT
		CamTable	: STRING[8] ;
		Periodic	: BOOL ;
		MasterOffset	: REAL ;
		SlaveOffset	: REAL ;
		MasterScaling	: REAL ;
		SlaveScaling	: REAL ;
		StartMode	: USINT ;
		MasterParID	: UINT ;
	END_STRUCT;
	AxisMoveVel_typ : STRUCT
		Velocity	: USINT ;
		Acceleration	: USINT ;
		Deceleration	: USINT ;
		Direction	: USINT ;
	END_STRUCT;
	AxisPosition_typ : STRUCT
		Position	: REAL ;
	END_STRUCT;
	AxisMoveAbs_typ : STRUCT
		Position	: REAL ;
		Velocity	: USINT ;
		Acceleration	: USINT ;
		Deceleration	: USINT ;
		Direction	: USINT ;
	END_STRUCT;
	AxisMove_typ : STRUCT
		Position	: ARRAY[0..8] OF AxisPosition_typ ;
		AbsMove	: ARRAY[0..8] OF AxisMoveAbs_typ ;
		VelMove	: ARRAY[0..1] OF AxisMoveVel_typ ;
		SyncMove	: AxisMoveSync_typ ;
	END_STRUCT;
	AxisConfig_typ : STRUCT
		INIT	: BOOL ;
		dig_in_reference	: UINT ;
		dig_in_pos_hw_end	: UINT ;
		dig_in_neg_hw_end	: UINT ;
		dig_in_trigger1	: UINT ;
		dig_in_trigger2	: UINT ;
		encoder_if_count_dir	: USINT ;
		encoder_if_units	: UDINT ;
		encoder_if_rev_motor	: UDINT ;
		limit_v_pos	: REAL ;
		limit_v_neg	: REAL ;
		limit_a1_pos	: REAL ;
		limit_a2_pos	: REAL ;
		limit_a1_neg	: REAL ;
		limit_a2_neg	: REAL ;
		limit_t_jolt	: REAL ;
		limit_t_in_pos	: REAL ;
		limit_pos_sw_end	: DINT ;
		limit_neg_sw_end	: DINT ;
		limit_ds_warning	: REAL ;
		limit_ds_stop	: REAL ;
		limit_a_stop	: REAL ;
		controller_mode	: SINT ;
		position_kv	: REAL ;
		position_tn	: REAL ;
		position_t_predict	: REAL ;
		position_t_total	: REAL ;
		position_p_max	: REAL ;
		position_i_max	: REAL ;
		speed_kv	: REAL ;
		speed_tn	: REAL ;
		speed_t_filter	: REAL ;
		speed_isq_filter1_type	: UINT ;
		speed_isq_filter1_a0	: REAL ;
		speed_isq_filter1_a1	: REAL ;
		speed_isq_filter1_b0	: REAL ;
		speed_isq_filter1_b1	: REAL ;
		speed_isq_filter1_b2	: REAL ;
		speed_isq_filter2_type	: UINT ;
		speed_isq_filter2_a0	: REAL ;
		speed_isq_filter2_a1	: REAL ;
		speed_isq_filter2_b0	: REAL ;
		speed_isq_filter2_b1	: REAL ;
		speed_isq_filter2_b2	: REAL ;
		speed_isq_filter3_type	: UINT ;
		speed_isq_filter3_a0	: REAL ;
		speed_isq_filter3_a1	: REAL ;
		speed_isq_filter3_b0	: REAL ;
		speed_isq_filter3_b1	: REAL ;
		speed_isq_filter3_b2	: REAL ;
		uf_type	: USINT ;
		uf_auto_config	: USINT ;
		uf_u0	: REAL ;
		uf_un	: REAL ;
		uf_fn	: REAL ;
		ff_torque_load	: REAL ;
		ff_torque_pos	: REAL ;
		ff_torque_neg	: REAL ;
		ff_kv_torque	: REAL ;
		ff_inertia	: REAL ;
		ff_t_filter_a	: REAL ;
		stop_decel_ramp	: USINT ;
		stop_controller	: USINT ;
		homing_s	: DINT ;
		homing_v_switch	: REAL ;
		homing_v_trigger	: REAL ;
		homing_a	: REAL ;
		homing_mode	: USINT ;
		homing_edge_sw	: USINT ;
		homing_start_dir	: USINT ;
		homing_trigg_dir	: USINT ;
		homing_ref_pulse	: USINT ;
		homing_tr_s_block	: REAL ;
	END_STRUCT;
END_TYPE